import pickle

Amour = ["amour","aime","baise","cœur","amoureux","tendresse","amitié","baiser","Cupidon","Aphrodite","passion","Éros","désir","sentiment","amant","affection","idylle","Vénus","attachement","attirance","platonique","compassion","plaisir","charité","érotique","haine","relation","beauté","adoration","aimer","philtre","altruisme","amourette","bien-aimé","érotisme","joie","mariage","romantique","courtois","émotion","déesse","éternel","luxure","bonheur","conjugal","jalousie","psyché","filial","fraternel","charnel","chaste","sexualité","dévotion","ivresse","philanthropie","couple","fidélité","tendre","sincère","volupté","Dieu","idolâtrie","piété","souffrance","troubadour","chant","chasteté","désespoir","libertinage","romantisme","solitude","désamour","poésie","sacrifice","poème","sensualité","sexuel","chagrin","romance","hymen","séduction","âme","dilection","lyrique","ode","thème","abnégation","bagatelle","bien-aimée","chanson","conquête","déclaration","désintéressement","fou","indifférence","passionné","adultère","amor","enchantement","femme","inceste"]
Argent = ["monnaie","métal","somme","banque","sou","thune","bourse","caisse","denier","argenterie","trésor","dépense","blé","fric","lingot","magot","dépenser","fonds","finance","flouze","oseille","crédit","rembourser","loterie","billet","pèze","amasser","créancier","maille","achat","avarice","écu","médaille","sac","jeu","payer","prêter","dette","pognon","richesse","blanchiment","débourser","prostitution","pute","rançon","rond","bijou","économiser","casino","dollar","papier","prêt","coffre","gucci","louis vuitton","gagner","précieux","dior","vendu","prix","fortune","précieux","bancaire","vendre","versement","impôt","poche","recette","salaire","volé","commerce","espèce","liquide","comptant","désargenter","diamant","gisement","loyer","mercenaire","contrôle","métallique","paiement","plaqué","rapporter","sesterce","vénal","argent","sale","chèque","empocher","endetté","escroquer","inflation","métal","blanc","minerai","radin","soutirer","sulfure","trésorerie","butin","économe","économie","financer","millionnaires","orfèvrerie","papier","PayPal","pièce","acheter","centime","virement","investissement","pièce","racket","transaction","banque","braquage","budget","échange","encaisser","produit","dépensier","verser","cagnotte","dévaliser","marchand","coûtait","milliardaire","montant","payement","tune","affaires"]
Drogue=['gue-dro','opium','cannabis','héroïne','trafic','céllophanée','cocaïne','trafiquant','alcool','stupéfiant','dope','médicament','toxicomanie','addiction','dépendance','psychotrope','dealer','dose','ecstasy','came','LSD','amphétamine','conso','crack','deal','fumette','substance','addictif','sniffer','toxicomane','narcotique','overdose','haschich','désintoxication','rave','tabac','cartel','intraveineuse','surdose','défonce','emprise','psychédélique','shooté','alcaloïde','gang','médicinal','narcoterroriste','marijuana','shit','accoutumance','bicrave','caïd','consommé','illicite','légalisation','manque','mélange','seringue','sexe','trafic de drogue','dopage','hallucinogène','morphine','poison','sevrage','procurer','toxico','compulsif','kétamine','méthamphétamine','narcotrafic','toxique','consommateur','criminalité','délinquance','effet','pharmacie','racket','réseau','vape','coke','Colombie','revendeur','alcoolisme','hallucination','injection','narcotrafiquant','orviétan','antidrogue','arsenic','bad trip','bicraveur','camelote','chlague','chnek','chnouf','choper','contrebande','daube','déchiré','dépouillé','désomorphine','droguier','droguiste','faya','fechnou','fly','foncedé','guedro','illégal','junkie','junky','leurdi','mafia','merde','meuca','meumeu','mixture','narco-État','palliatif','pécho','pété','pharmacologie','police','potion','pouilledé','psychoactif','purge','schnouf','schnouff','se camer','se shooter','séquelle','shoot','stone','stup','Tox','célophané','toxine','trip','triper','tripper','usager','venin','virus']

with open('Amourpickle','wb') as L1:
    pickle.dump(Amour,L1)
with open('Amourpickle','rb') as L1:
    Liste_amour = pickle.load(L1)
    print(Liste_amour)

with open('Argentpickle','wb') as L2:
    pickle.dump(Argent,L1)
with open('Argentpickle','rb') as L2:
    Liste_argent = pickle.load(L2)
    print(Liste_argent)

